### ISSUE TITLE
运行vessel_segmentation_train.py报错

### ISSUE THREAD

**Issue by MAOMAOvv1** [Qsingle/imed_vision#4]
你好，我在运行vessel_segmentation_train.py文件的时候，出现了这个错误
File "/home/mht/PycharmProjects/imed_vision-main/vessel_segmentation_train.py", line 590, in main_worker
    writer.add_scalar("validation/{}".format(metric), result[metric][1], global_step=epoch)
KeyError: 'specifity'
主要是单词specifity和metric.py文件中的specificity不一致引起的

**Comment by Qsingle** [comment]
> 你好，我在运行vessel_segmentation_train.py文件的时候，出现了这个错误 File "/home/mht/PycharmProjects/imed_vision-main/vessel_segmentation_train.py", line 590, in main_worker writer.add_scalar("validation/{}".format(metric), result[metric][1], global_step=epoch) KeyError: 'specifity' 主要是单词specifity和metric.py文件中的specificity不一致引起的

我们将会在后期修复这个bug
